---

- name: Ensure hostname is resolvable
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"

- name: Ensure go group
  become: yes
  group:
    name: "{{ gocd_server.group }}"
    state: present

- name: Ensure go user
  become: yes
  user:
    name: "{{ gocd_server.user }}"
    comment: Go CD User
    group: "{{ gocd_server.group }}"
    home: "{{ gocd_server.user_dir }}"

- name: Install some dependencies
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - git
    - tree

- name: add Go CD apt repository key
  become: yes
  apt_key:
    url: "{{ gocd_server.apt_key_url }}"

- name: add GO CD apt repository
  become: yes
  apt_repository:
    repo: "deb {{ gocd_server.repo_url }} /"
    state: present

- name: Install go-server
  become: yes
  apt:
    name: "go-server={{ gocd_server.version }}"
    state: present
    force: yes

- name: Add go-server to autostart
  become: yes
  service:
    name: go-server
    enabled: yes
    state: stopped
