---

- name: Create various directories
  become: yes
  file:
    path: "{{ gocd_server.user_dir }}/{{ item }}"
    state: directory
    owner: "{{ gocd_server.user }}"
    group: "{{ gocd_server.group }}"
  with_items:
    - work/go-server

- name: Ensures go-server configuration
  become: yes
  template:
    src: defaults.j2
    dest: /etc/default/go-server
    owner: "{{ gocd_server.user }}"
    group: "{{ gocd_server.group }}"
  notify:
    - restart go-server

- name: Ensures go-server passwd file
  become: yes
  template:
    src: passwd.j2
    dest: "{{ gocd_server.user_dir }}/passwd"
    owner: "{{ gocd_server.user }}"
    group: "{{ gocd_server.group }}"
    mode: 0540
  when: gocd_server.passwd_users

- name: Ensure gocd server is running
  become: yes
  service:
    name: go-server
    state: started
